In [200]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

dataset = pd.read_csv('train.csv')

dataset.describe()

,index,beer/ABV,beer/beerId,beer/brewerId,review/appearance,review/aroma,review/overall,review/palate,review/taste,review/timeUnix,user/ageInSeconds,user/birthdayUnix
count,37500.000000,37500.000000,37500.000000,37500.000000,37500.000000,37500.000000,37500.00000,37500.000000,37500.000000,3.750000e+04,7.856000e+03,7.856000e+03
mean,24951.887573,7.403725,21861.152027,3036.595120,3.900053,3.873240,3.88944,3.854867,3.922440,1.232794e+09,1.176705e+09,2.416303e+08
std,14434.009669,2.318145,18923.130832,5123.084675,0.588778,0.680865,0.70045,0.668068,0.716504,7.190955e+07,3.375514e+08,3.375514e+08
min,0.000000,0.100000,175.000000,1.000000,0.000000,1.000000,0.00000,1.000000,1.000000,9.262944e+08,7.034366e+08,-2.208960e+09
25%,12422.500000,5.400000,5441.000000,395.000000,3.500000,3.500000,3.50000,3.500000,3.500000,1.189194e+09,9.794810e+08,1.433628e+08
50%,24942.500000,6.900000,17538.000000,1199.000000,4.000000,4.000000,4.00000,4.000000,4.000000,1.248150e+09,1.100009e+09,3.183264e+08
75%,37416.750000,9.400000,34146.000000,1315.000000,4.500000,4.500000,4.50000,4.500000,4.500000,1.291330e+09,1.274973e+09,4.388544e+08
max,49999.000000,57.700000,77207.000000,27797.000000,5.000000,5.000000,5.00000,5.000000,5.000000,1.326267e+09,3.627295e+09,7.148988e+08

In [201]:
dataset.head(5)

,index,beer/ABV,beer/beerId,beer/brewerId,beer/name,beer/style,review/appearance,review/aroma,review/overall,review/palate,review/taste,review/text,review/timeStruct,review/timeUnix,user/ageInSeconds,user/birthdayRaw,user/birthdayUnix,user/gender,user/profileName
0,40163,5.0,46634,14338,Chiostro,Herbed / Spiced Beer,4.0,4.0,4.0,4.0,4.0,Pours a clouded gold with a thin white head. N...,"{'min': 38, 'hour': 3, 'mday': 16, 'sec': 10, ...",1229398690,NaN,NaN,NaN,NaN,RblWthACoz
1,8135,11.0,3003,395,Bearded Pat's Barleywine,American Barleywine,4.0,3.5,3.5,3.5,3.0,12oz bottle into 8oz snifter.\t\tDeep ruby red...,"{'min': 38, 'hour': 23, 'mday': 8, 'sec': 58, ...",1218238738,NaN,NaN,NaN,NaN,BeerSox
2,10529,4.7,961,365,Naughty Nellie's Ale,American Pale Ale (APA),3.5,4.0,3.5,3.5,3.5,First enjoyed at the brewpub about 2 years ago...,"{'min': 7, 'hour': 18, 'mday': 26, 'sec': 2, '...",1101492422,NaN,NaN,NaN,Male,mschofield
3,44610,4.4,429,1,Pilsner Urquell,Czech Pilsener,3.0,3.0,2.5,3.0,3.0,First thing I noticed after pouring from green...,"{'min': 7, 'hour': 1, 'mday': 20, 'sec': 5, 'y...",1308532025,1.209827e+09,"Aug 10, 1976",208508400.0,Male,molegar76
4,37062,4.4,4904,1417,Black Sheep Ale (Special),English Pale Ale,4.0,3.0,3.0,3.5,2.5,A: pours an amber with a one finger head but o...,"{'min': 51, 'hour': 6, 'mday': 12, 'sec': 48, ...",1299912708,NaN,NaN,NaN,NaN,Brewbro000

In [202]:
dataset.drop(['index','review/appearance','review/aroma','review/palate','review/taste','beer/brewerId','beer/beerId', 'user/ageInSeconds', 'user/birthdayRaw', 'user/birthdayUnix', 'user/gender', 'user/profileName', 'review/timeStruct', 'review/timeUnix'], axis=1, inplace=True)

In [203]:
dataset.head(5)

,beer/ABV,beer/name,beer/style,review/overall,review/text
0,5.0,Chiostro,Herbed / Spiced Beer,4.0,Pours a clouded gold with a thin white head. N...
1,11.0,Bearded Pat's Barleywine,American Barleywine,3.5,12oz bottle into 8oz snifter.\t\tDeep ruby red...
2,4.7,Naughty Nellie's Ale,American Pale Ale (APA),3.5,First enjoyed at the brewpub about 2 years ago...
3,4.4,Pilsner Urquell,Czech Pilsener,2.5,First thing I noticed after pouring from green...
4,4.4,Black Sheep Ale (Special),English Pale Ale,3.0,A: pours an amber with a one finger head but o...

In [204]:
y=dataset['review/text'].values
print(y)

['Pours a clouded gold with a thin white head. Nose is quite floral with a larger amount of spices added. Definitely a spice forward fragrance. Flavor has an odd burn that hits on the first sip. After it fades it seems like a dirty vanilla aftertaste. Perhaps this is the absinthe? Regardless of that, I get a quite spiced tone on the tongue. Almost feel a little heat from it. I think that my inexperienced palate on these spices is contributing to my ignorance of what precisely they are. Overall a nice drinker indeed.'
 "12oz bottle into 8oz snifter.\t\tDeep ruby red hue with a one finger light tan head that settles to a thin rim along the glass.\t\tSharp piercing hops with some light hard candy in the background. \t\tThe hops provide some bitterness, but they aren't as sharp as I would have expected. Mostly a light candy flavor like in the aroma. Full bodied with good carbonation. The finish is some lingering sweet flavor with a bit of bitterness.\t\tA very sweet barleywine with a weird hard candy flavor that seemed to dominate. Not bad, but I would have liked a little more complexity."
 'First enjoyed at the brewpub about 2 years ago, I finally managed to get a bottle.\tSlightly hazy orange-amber topped with a two finger foamy white head.\tVery nice fruity aroma, soft and floral, tea and toast.\tFruity, slightly grapefruity hop note, toast and biscuity malt balance. Hoppier and more floral when it warms up.\tLight-medium bodied, liked it better on draft but still a solid beer.'
 ...
 'Sampled on tap at Redbones.\t\tThis marzen style beer poured a clear, copper color with white foam that settled. The smell was a mild, slightly sweet malty aroma. The taste was slightly sweet (but less sweet than many other of this style) and tangy, malty, with the hops making their presence felt in the finish. There was also a bit of a dry, oaky flavor. The mouthfeel was smooth and creamy up front, but with a dry finish. The body and carbonation were medium. The aftertaste was dry and lingered nicely. This was a good oktoberfest beer.'
 "Pours a black body with a brown head that very quickly fizzles away to a thin brown lace.\t\tAroma smells of coffee beans, bourbon, chocolate, malt.\t\tTaste a lot of bourbon and coffee right off the bat. Then, hints of chocolate and something very sweet like a syrup. After letting the beer settle I find the flavors come more together as it warms up. An incredibly tasty stout.\t\tMouthfeel is very impressive. Thick, but not too thick with a velvet like feel.\t\tThis beer is heavy and fills you up, also 11.20% so its not a beer you need to drink a whole lot of. Still though, you might find it hard to pass up another glass.\t\tOverall this beer is one of the best stouts i'm yet to have."
 'A nice sweet, malty beer...nothing complex, just a smooth refreshing drink that reveals no hint of 8.3 abv.\t\tPours an ice-tea colored brown. If held to the light, the very center of the beer is dense. Lots of light comes through on the sides. Tan head is average size with poor retention. Good lacing. Smell and taste are of caramel malts. Must be balanced very well because it is quite sweet but not cloying or too sweet for mass consumption. Mouthfeel is thick and rich. Drinkability is good. I finished off the 12 oz bottle quickly and could have enjoyed more.\t\tThis is one you have to be in the mood for, but if you are looking for something well made and sweet, this will do it for you.']

# Text Preprocessing

In [205]:
import string
import re
import nltk
from nltk.corpus import stopwords
import num2words

def clean_doc(review):
# split into tokens by white space
    #print(review)
    review=str(review)
    tokens = review.split()
    #print(tokens)
# prepare regex for char filtering
    re_punc = re.compile('[%s]' % re.escape(string.punctuation)) # remove punctuation from each word
    tokens = [re_punc.sub('', w) for w in tokens]
# remove remaining tokens that are not alphabetic
   # tokens = [word for word in tokens if word.isalpha()]
# filter out stop words
    stop_words = set(stopwords.words('english'))
    tokens = [w for w in tokens if not w in stop_words]
# filter out short tokens
    tokens = [word for word in tokens if len(word) > 1]
    
      
    #for i in tokens:
      #  if i.isdigit():
          #  i= num2words(i)
        
    return tokens

In [206]:
def doc_to_line(tokens):
  
  tokens = clean_doc(tokens)
  # filter by vocab
  tokens = [w.lower() for w in tokens] 
  #lemmatizing and stemming
  #review = ' '.join([stemmer.stem(lemmatizer.lemmatize(word, pos='a')) for word in review.split()])
  return ' '.join(tokens)

In [216]:
dataset['processed_text'] = dataset['review/text'].map(doc_to_line).astype(str)
dataset['processed_style'] = dataset['beer/style'].map(doc_to_line).astype(str)
dataset['processed_name'] = dataset['beer/name'].map(doc_to_line).astype(str)

In [217]:
dataset.head(5)

,beer/ABV,beer/name,beer/style,review/overall,review/text,processed_text,processed_style,processed_name
0,5.0,Chiostro,Herbed / Spiced Beer,4.0,Pours a clouded gold with a thin white head. N...,pours clouded gold thin white head nose quite ...,herbed spiced beer,chiostro
1,11.0,Bearded Pat's Barleywine,American Barleywine,3.5,12oz bottle into 8oz snifter.\t\tDeep ruby red...,12oz bottle 8oz snifter deep ruby red hue one ...,american barleywine,bearded pats barleywine
2,4.7,Naughty Nellie's Ale,American Pale Ale (APA),3.5,First enjoyed at the brewpub about 2 years ago...,first enjoyed brewpub years ago finally manage...,american pale ale apa,naughty nellies ale
3,4.4,Pilsner Urquell,Czech Pilsener,2.5,First thing I noticed after pouring from green...,first thing noticed pouring green bottle glass...,czech pilsener,pilsner urquell
4,4.4,Black Sheep Ale (Special),English Pale Ale,3.0,A: pours an amber with a one finger head but o...,pours amber one finger head strong pour head r...,english pale ale,black sheep ale special

In [218]:
word_freq = dataset.processed_text.apply(lambda x : ' '.join(set(x.split()))).str.split(expand=True).stack().value_counts()
most_common_words = set(word_freq[ word_freq > 18000].keys()).difference({'not', 'sweet', 'flavor'})
least_common_words = set(word_freq[ word_freq < 4].keys())
# we shall remove both type of words and some others as necessary
undesirable_words = most_common_words.union(least_common_words).union({'drink', 'drinabl', 'and', 'like'})

In [219]:
def remove_words(review):
    review=str(review)
    return ' '.join(list(filter(lambda word : word not in undesirable_words, review.split())))

In [220]:
dataset['processed_text'] = dataset['processed_text'].map(remove_words)

In [221]:
dataset.head(5)

,beer/ABV,beer/name,beer/style,review/overall,review/text,processed_text,processed_style,processed_name
0,5.0,Chiostro,Herbed / Spiced Beer,4.0,Pours a clouded gold with a thin white head. N...,pours clouded gold thin white nose quite flora...,herbed spiced beer,chiostro
1,11.0,Bearded Pat's Barleywine,American Barleywine,3.5,12oz bottle into 8oz snifter.\t\tDeep ruby red...,12oz bottle 8oz snifter deep ruby red hue one ...,american barleywine,bearded pats barleywine
2,4.7,Naughty Nellie's Ale,American Pale Ale (APA),3.5,First enjoyed at the brewpub about 2 years ago...,first enjoyed brewpub years ago finally manage...,american pale ale apa,naughty nellies ale
3,4.4,Pilsner Urquell,Czech Pilsener,2.5,First thing I noticed after pouring from green...,first thing noticed pouring green bottle glass...,czech pilsener,pilsner urquell
4,4.4,Black Sheep Ale (Special),English Pale Ale,3.0,A: pours an amber with a one finger head but o...,pours amber one finger strong pour recedes lig...,english pale ale,black sheep ale special